codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: "40...90"

  status:
    project:
      default:
        target: 75%
        threshold: 5%
    patch:
      default:
        target: 75%
        threshold: 5%
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: no
  require_base: no