version: 2.1

orbs:
  android: circleci/android@2.4.0
  codecov: codecov/codecov@4.0.1

workflows:
  version: 2
  aepsdk-assurance-ci: 
    jobs:
      - build-and-unit-test
      - functional-test

jobs:
  build-and-unit-test:
    executor:
      name: android/android-docker
      resource-class: large
      tag: 2024.01.1

    steps:
      - checkout

      - run:
          name: Check format
          command: make checkformat

      - run:
          name: Assemble Phone Release
          command: make assemble-phone-release

      - run:
          name: Run Assurance Unit Tests with coverage
          command: make unit-test-coverage

      - codecov/upload:          
          file: ./code/assurance/build/reports/coverage/test/phone/debug/report.xml
          flags: unit-tests

      - store_test_results:
          path: code/assurance/build/test-results/

      - store_artifacts:
          path: code/assurance/build/reports

      - run:
          name: Generate JavaDoc
          command: make javadoc


  functional-test:
      executor:
        name: android/android-machine
        resource-class: large
        tag: 2024.01.1

      steps:
        - checkout
        
        - android/start-emulator-and-run-tests:
            system-image: system-images;android-29;default;x86
            post-emulator-launch-assemble-command: make assemble-phone-release
            test-command: make functional-test-coverage

        - codecov/upload:
            file: "./code/core/build/reports/coverage/androidTest/phone/debug/connected/report.xml"
            flags: functional-tests

        - store_artifacts:
            path: code/assurance/build/reports

        - store_test_results:
            path: code/assurance/build/outputs/androidTest-results
