name: Update Assurance Test App APK

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to be used when updating AssuranceTestApp'
        required: true

jobs:
  update-testapp:
    runs-on: macos-14
    steps:
    - name: Set up Java
      uses: actions/setup-java@v4.6.0
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Generate AssuranceTestApp APK
      run: make build-app

    - name: Create pull request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
        branch_name="update-assurance-test-app-apk"
        git checkout -b "$branch_name"
        git add .
        git commit -m "Update Assurance Test App APK"
        git push origin "$branch_name"
    
        gh pr create \
          --base "${{ github.event.inputs.branch }}" \
          --head "$branch_name" \
          --title "Update AssuranceTestApp APK" \
          --body "Update AssuranceTestApp APK"
    