name: Update Assurance Test App APK

on: workflow_dispatch

jobs:
  update-testapp:
    runs-on: macos-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3.1.0
      with:
        ref: dev

    - name: Generate AssuranceTestApp APK
      run: make build-app

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Update Assurance Test App APK
        title: Update AssuranceTestApp APK
        base: dev
