name: Update Assurance Test App APK

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to be used when updating AssuranceTestApp'
        required: true

jobs:
  update-testapp:
    runs-on: macos-latest

    steps:
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Checkout
      uses: actions/checkout@v3.1.0
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Generate AssuranceTestApp APK
      run: make build-app

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Update Assurance Test App APK
        title: Update AssuranceTestApp APK
        base: ${{ github.event.inputs.branch }}
